-
  url_name: Train_to_the_End_of_the_World
  name: Куда едет поезд судного дня?
  trailer: https://www.youtube.com/embed/XLWzhcMOcVo?si=GeS6KO7BuweEXmJV
  releaseYear: '2024-01-01'
  review: 7.38
  description: >-
    В непримечательном на первый взгляд провинциальном городке с жителями происходят странные вещи. Однако Сидзуру Тикура больше беспокоится о своей пропавшей подруге. Решив найти её, Сидзуру вместе с тремя другими девочками садится на заброшенный поезд и отправляется во внешний мир, не зная, смогут ли они вернуться живыми. Что ждёт их на конечной остановке?
  portraitImgName: trainTotheEndoftheWorld.jpg
  studios:
    - EMT squared
  typeName: Сериал
  franchise: Train_to_the_End_of_the_World
  genres:
    - Приключения
- description: Краткий пересказ событий первых одиннадцати эпизодов аниме-сериала «Куда едет поезд судного дня?».
  franchise: Train_to_the_End_of_the_World
  genres:
    - Приключения
  name: Куда едет поезд судного дня? Рекап
  portraitImgName: Train_to_the_End_of_the_World_Recap.jpeg
  releaseYear: '2024-01-01'
  review: 5.99
  studios:
    - EMT squared
  trailer: https://www.youtube.com/embed/XLWzhcMOcVo?si=GeS6KO7BuweEXmJV
  typeName: TV Спецвыпуск
  url_name: Train_to_the_End_of_the_World_Recap